# Generated by Django 5.2.9 on 2026-01-26 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minilibrary', '0002_genre_book_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genre',
            new_name='genres',
        ),
    ]
